FROM mistp/openui

# Install any required packages if needed
# RUN apt-get update && apt-get install -y <package-names>

# Expose port if needed
EXPOSE 7878

# Set environment variable (better to pass it during `docker run`)
ENV OPENAI_API_KEY=sk-TIEncoAfE6whm1VU76DdCe93B4Ed44C4A2F65199E94a3e3d